[project]
name = 'LiquidStack'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.lending-pool]
path = 'contracts/lending-pool.clar'
clarity_version = 2
epoch = 2.5

[contracts.v]
path = 'contracts/v.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
